run:
  timeout: 5m
  go: "1.22"
  issues-exit-code: 1

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - gofmt
    - goimports
    - errcheck
  disable:
    - depguard

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/port-experimental/port-go-sdk
issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
